# Originally forked from https://github.com/AnacondaRecipes/cudatoolkit-feedstock
# Distributed under the BSD-2-Clause license
# Copyright (c) 2017, Continuum Analytics, Inc. All rights reserved.
#
# Distribution of the content approved by NVIDIA ( http://nvbugs/3052604 )
{% set major_minor = major_minor_ver|default("11.0") %}

# The following cudavars dictionary is a table of metadata for selecting various
# paramaters based on the X.Y version number of cudatoolkit. The following is a description
# of the keys for each entry:
#
# version: the X.Y.Z version number for cudatoolkit.
# version_patch: the patch/build number for the associated X.Y.Z number. This value
#   is a dict of platform keys to patch numbers, because this value is platform dependent.
#   If the value of the version_patch is "skip", that platform will be skipped.
# subdomain: The nvidia.com subdomain where that files may be downloaded.
# download_dir: The directory in which a version's downloads exist. This does not
#   follow a set pattern. The URL that is accessed for download is usually:
#       https://{{ subdomain }}.nvidia.com/compute/cuda/{{ download_dir }}
# checksums: Another platform dependent key of the various download file checksums. For the
#   runfiles, these are take from the official MD5 checksums. The official MD5 sums are
#   usually available at the following 11.0+:
#       https://{{ subdomain }}.nvidia.com/compute/cuda/{{ download_dir }}/docs/sidebar/md5sum.txt
#   For 10.1.243, the URL is:
#       http://developer.download.nvidia.com/compute/cuda/10.1/Prod/docs3/sidebar/md5sum.txt
#   For 10.0.130, the URL differs by the subdir:
#       https://developer.download.nvidia.com/compute/cuda/10.0/Prod/docs/sidebar/md5sum.txt
#   For 9.2.148, the URL is:
#       http://developer.download.nvidia.com/compute/cuda/9.2/Prod2/docs/sidebar/md5sum.txt
# sysroot_version: The version of sysroot_linux-64 that will be used. Currently only used
#   on linux64. If this key is not present, then no sysroot requirement is used.

{% set cudavars = {
  "9.2": {
    "version": "9.2.148",
    "version_patch": {
      "linux64": "396.37",
      "osx": "skip",
      "ppc64le": "skip",
      "win": "",
    },
    "subdomain": "developer",
    "download_dir": major_minor + "/Prod2",
    "checksums": {
      "linux64": "8303cdf46904e6dea8d5d641b0b46f0d",
      "win": "efaf92a93bdef21da29aba8a8768a16d",
    },
    "blob_ext": {
      "linux64": "",
      "win": "",
    },
  },
  "10.0": {
    "version": "10.0.130",
    "version_patch": {
      "linux64": "410.48",
      "osx": "skip",
      "ppc64le": "skip",
      "win": "411.31",
    },
    "subdomain": "developer",
    "download_dir": major_minor + "/Prod",
    "checksums": {
      "linux64": "9375304c8dc8d42e7f9a9ae37e80b42b",
      "win": "90fafdfe2167ac25432db95391ca954e",
    },
    "blob_ext": {
      "linux64": "",
      "win": "",
    },
  },
  "10.1": {
    "version": "10.1.243",
    "version_patch": {
      "linux64": "418.87.00",
      "osx": "skip",
      "ppc64le": "skip",
      "win": "426.00",
    },
    "subdomain": "developer.download",
    "download_dir": major_minor + "/Prod",
    "checksums": {
      "linux64": "a71f703ed688eeca637dc27df714e854",
      "ppc64le": "abb32a3754c84d2934ef04a76a9bc978",
      "win": "b54cf32683f93e787321dcc2e692ff69",
    },
    "blob_ext": {
      "linux64": ".run",
      "ppc64le": ".run",
      "win": ".exe",
    },
  },
  "10.2": {
    "version": "10.2.89",
    "version_patch": {
      "linux64": "440.33.01",
      "osx": "skip",
      "ppc64le": "440.33.01",
      "win": "441.22",
    },
    "subdomain": "developer.download",
    "download_dir": major_minor + "/Prod",
    "checksums": {
      "linux64": "3d816c583759efa8567a92c1a2af90db",
      "ppc64le": "ecb6af432e64bc10e7a18cd6bd4be62f",
      "win": "d9f5b9f24c3d3fc456a3c789f9b43419",
    },
    "blob_ext": {
      "linux64": ".run",
      "ppc64le": ".run",
      "win": ".exe",
    },
  },
  "11.0": {
    "version": "11.0.3",
    "version_patch": {
      "linux64": "450.51.06",
      "osx": "skip",
      "ppc64le": "450.51.06",
      "win": "451.82",
    },
    "subdomain": "developer.download",
    "download_dir": "11.0.3",
    "checksums": {
      "linux64": "70af4cebe30549b9995fb9c57d538214",
      "ppc64le": "dabba7135b466d6726eade724d2eb598",
      "win": "80ae0fdbe04759123f3cab81f2aadabd",
    },
    "blob_ext": {
      "linux64": ".run",
      "ppc64le": ".run",
      "win": ".exe",
    },
    "sysroot_version": "2.17",
  },
}
%}
{% set version = cudavars[major_minor]["version"] %}
{% set version_patch = cudavars[major_minor]["version_patch"]["linux64"] %}  # [linux64]
{% set version_patch = cudavars[major_minor]["version_patch"]["osx"] %}  # [osx]
{% set version_patch = cudavars[major_minor]["version_patch"]["ppc64le"] %}  # [ppc64le]
{% set version_patch = cudavars[major_minor]["version_patch"]["win"] %}  # [win]
{% set subdomain = cudavars[major_minor]["subdomain"] %}
{% set download_dir = cudavars[major_minor]["download_dir"] %}

# Set runfile
{% if version_patch == "" %}
    {% set version_patch_underscore = "" %}
{% else %}
    {% set version_patch_underscore = "_" %}
{% endif %}
{% set runfile_pre = "cuda_" + version + version_patch_underscore + version_patch %}
{% set runfile = runfile_pre + "_linux" + cudavars[major_minor]["blob_ext"].get("linux64", "NONE") %}  # [linux64]
{% set runfile = runfile_pre + "_mac" + cudavars[major_minor]["blob_ext"].get("osx", "NONE") %}  # [osx]
{% set runfile = runfile_pre + "_linux_ppc64le" + cudavars[major_minor]["blob_ext"].get("ppc64le", "NONE") %}  # [ppc64le]
{% set runfile = runfile_pre + "_win10" + cudavars[major_minor]["blob_ext"].get("win", "NONE") %}  # [win]


package:
   name: cudatoolkit
   # match the package version to the libcudart.so version
   version: {{ version }}

source:
  - path: ./build.py
  - fn: {{ runfile }}
    url: https://{{ subdomain }}.nvidia.com/compute/cuda/{{ download_dir }}/local_installers/{{ runfile }}
    md5: {{ cudavars[major_minor]["checksums"]["linux64"] }}  # [linux64]
    md5: {{ cudavars[major_minor]["checksums"]["osx"] }}  # [osx]
    md5: {{ cudavars[major_minor]["checksums"]["ppc64le"] }}  # [ppc64le]
    md5: {{ cudavars[major_minor]["checksums"]["win"] }}  # [win]

build:
  number: 2
  script_env:
    - NVTOOLSEXT_INSTALL_PATH
    - DEBUG_INSTALLER_PATH
  missing_dso_whitelist:
    - "$RPATH/libdl.so.2"
    - "$RPATH/libpthread.so.0"
    - "$RPATH/libc.so.6"
    - "$RPATH/librt.so.1"
    - "$RPATH/ld-linux-x86-64.so.2"
    - "$RPATH/libm.so.6"
{% if version_patch == "skip" %}
  skip: true
{% endif %}
  rpaths_patcher: LIEF  # [ppc64le]
  script: |
    python build.py --version={{ version }} --version-patch={{ version_patch }} --runfile={{ runfile }}
    if errorlevel 1 exit 1                                                 # [win]

    :: copy nvvm and libdevice into the DLLs folder so numba can use them  # [win]
    mkdir "%PREFIX%\DLLs"                                                  # [win]
    xcopy /s /y "%PREFIX%\Library\bin\nvvm*" "%PREFIX%\DLLs\"              # [win]
    if errorlevel 1 exit 1                                                 # [win]
    xcopy /s /y "%PREFIX%\Library\bin\libdevice*" "%PREFIX%\DLLs\"         # [win]
    if errorlevel 1 exit 1                                                 # [win]


requirements:
  build:
    - 7za  # [win]
    - python >=3.7
    # for run_exports
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
{% if "sysroot_version" in cudavars[major_minor] %}
    - sysroot_linux-64 {{ cudavars[major_minor]["sysroot_version"] }}  # [linux64]
{% endif %}
  run_constrained:
    - __cuda >={{ major_minor }}

test:
  requires:
    - numba
    - python >=3.7
    - setuptools  # for pkg_resources

about:
  home: https://developer.nvidia.com/cuda-toolkit
  # A LicenceRef cannot be used in this case, see:
  # https://github.com/conda-forge/staged-recipes/pull/12882#discussion_r504086944
  license: NVIDIA End User License Agreement
  license_file: NVIDIA_EULA
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  description: |
    CUDA is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs). With CUDA, developers can dramatically speed up computing applications by harnessing the power of GPUs.

    The CUDA Toolkit from NVIDIA provides everything you need to develop GPU-accelerated applications. This CUDA Toolkit includes GPU-accelerated libraries, and the CUDA runtime for the Conda ecosystem. For the full CUDA Toolkit with a compiler and development tools visit https://developer.nvidia.com/cuda-downloads

    License Agreements
    The packages are governed by the CUDA Toolkit End User License Agreement (EULA). By downloading and using the packages, you accept the terms and conditions of the CUDA EULA - https://docs.nvidia.com/cuda/eula/index.html
  summary: 'CUDA Toolkit - Including CUDA runtime and headers'
  doc_url: https://docs.nvidia.com/cuda/
  dev_url: https://developer.nvidia.com/cuda-downloads

extra:
  recipe-maintainers:
    - scopatz
    - mike-wendt
    - jakirkham
    - raydouglass
    - kkraus14
    - leofang
