azure:
  store_build_artifacts: true
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
choco:
- cuda --version=11.4.2.47141
github:
  branch_name: main
  tooling_branch_name: main
