# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_major_minor_ver10.0providerconda:
        CONFIG: linux_64_major_minor_ver10.0providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver10.0providerexternal:
        CONFIG: linux_64_major_minor_ver10.0providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver10.1providerconda:
        CONFIG: linux_64_major_minor_ver10.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver10.1providerexternal:
        CONFIG: linux_64_major_minor_ver10.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver10.2providerconda:
        CONFIG: linux_64_major_minor_ver10.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver10.2providerexternal:
        CONFIG: linux_64_major_minor_ver10.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.0providerconda:
        CONFIG: linux_64_major_minor_ver11.0providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.0providerexternal:
        CONFIG: linux_64_major_minor_ver11.0providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.1providerconda:
        CONFIG: linux_64_major_minor_ver11.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.1providerexternal:
        CONFIG: linux_64_major_minor_ver11.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2.1providerconda:
        CONFIG: linux_64_major_minor_ver11.2.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2.1providerexternal:
        CONFIG: linux_64_major_minor_ver11.2.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2.2providerconda:
        CONFIG: linux_64_major_minor_ver11.2.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2.2providerexternal:
        CONFIG: linux_64_major_minor_ver11.2.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2providerconda:
        CONFIG: linux_64_major_minor_ver11.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver11.2providerexternal:
        CONFIG: linux_64_major_minor_ver11.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver9.2providerconda:
        CONFIG: linux_64_major_minor_ver9.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_major_minor_ver9.2providerexternal:
        CONFIG: linux_64_major_minor_ver9.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_major_minor_ver10.0providerconda:
        CONFIG: linux_ppc64le_major_minor_ver10.0providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver10.0providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver10.0providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver10.1providerconda:
        CONFIG: linux_ppc64le_major_minor_ver10.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver10.1providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver10.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver10.2providerconda:
        CONFIG: linux_ppc64le_major_minor_ver10.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver10.2providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver10.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.0providerconda:
        CONFIG: linux_ppc64le_major_minor_ver11.0providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.0providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver11.0providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.1providerconda:
        CONFIG: linux_ppc64le_major_minor_ver11.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.1providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver11.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2.1providerconda:
        CONFIG: linux_ppc64le_major_minor_ver11.2.1providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2.1providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver11.2.1providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2.2providerconda:
        CONFIG: linux_ppc64le_major_minor_ver11.2.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2.2providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver11.2.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2providerconda:
        CONFIG: linux_ppc64le_major_minor_ver11.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver11.2providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver11.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver9.2providerconda:
        CONFIG: linux_ppc64le_major_minor_ver9.2providerconda
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_major_minor_ver9.2providerexternal:
        CONFIG: linux_ppc64le_major_minor_ver9.2providerexternal
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)